/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-11-05 18:26:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.usuario;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cadastrarUsuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/maicon/Documents/recode/Entrega-mod4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Valonge/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153395882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1696858713290L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjstl_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fjstl_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fjstl_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../assets/css/style_home.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"./assets/images/logo.png\"\r\n");
      out.write("	type=\"image/x-icon\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<title>Vá longe - Cadastre-se</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg bg-warning\" data-bs-theme=\"dark\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"../index.jsp\"><img src=\"../assets/images/logo.png\" alt=\"logo va longe\"></a>\r\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("                    data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\"\r\n");
      out.write("                    aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"collapse navbar-collapse  justify-content-end text-center\" id=\"navbarSupportedContent\">\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                    <ul class=\"navbar-nav mb-2 mb-lg-0\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link style_link_hover\" aria-current=\"page\" href=\"../index.jsp\">\r\n");
      out.write("                                Home</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link style_link_hover\" aria-current=\"page\" href=\"cadastrar\">\r\n");
      out.write("                                Cadastrar-se</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link style_link_hover\" href=\"../destino/cadastrarDestino.jsp\">\r\n");
      out.write("                                Cadastrar destino\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link style_link_hover\" href=\"../contact.html\">\r\n");
      out.write("                                Contato\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                       \r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div class=\"container my-5 py-5 border border-primary-subtle rounded\">\r\n");
      out.write("    \r\n");
      out.write("    <form class=\"row g-3\" action=\"cadastrar\" method=\"POST\">\r\n");
      out.write("				<input type=\"hidden\" name=\"inputUsuario\" value=\"client\">\r\n");
      out.write("    <div class=\"col-md-6\">\r\n");
      out.write("      <label for=\"inputNome\" class=\"form-label\">Nome</label>\r\n");
      out.write("      <input type=\"text\"  required maxlength=\"50\" class=\"form-control\" id=\"inputNome\" name=\"inputNome\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-md-6\">\r\n");
      out.write("      <label for=\"inputEmail\" class=\"form-label\">Email</label>\r\n");
      out.write("      <input type=\"email\" required maxlength=\"50\" class=\"form-control\" id=\"inputEmail\" name=\"inputEmail\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-md-4\">\r\n");
      out.write("      <label for=\"inputCpf\" class=\"form-label\">CPF</label>\r\n");
      out.write("      <input type=\"text\" oninput=\"mascara(this)\" required class=\"form-control\" id=\"inputCpf\" name=\"inputCpf\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-md-4\">\r\n");
      out.write("      <label for=\"inputRg\" class=\"form-label\">RG</label>\r\n");
      out.write("      <input type=\"text\" maxlength=\"9\" required class=\"form-control\" id=\"inputRg\" name=\"inputRg\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-md-4\">\r\n");
      out.write("      <label for=\"inputTel\" class=\"form-label\">Telefone</label>\r\n");
      out.write("      <input type=\"tel\" required maxlength=\"15\" oninput=\"handlePhone(event)\" class=\"form-control\" id=\"inputTel\" name=\"inputTel\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-md-3\">\r\n");
      out.write("      <label for=\"inputNascimento\" class=\"form-label\">Data de nascimento</label>\r\n");
      out.write("      <input type=\"date\" required class=\"form-control\" id=\"inputNascimento\" name=\"inputNascimento\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-md-3\">\r\n");
      out.write("      <label for=\"inputSenha\" class=\"form-label\">Senha</label>\r\n");
      out.write("      <input type=\"password\" maxlength=\"32\" required class=\"form-control\" id=\"inputSenha\" name=\"inputSenha\">\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("      <div class=\"col-4\">\r\n");
      out.write("        <label for=\"inputEndereco\" class=\"form-label\">Endereço</label>\r\n");
      out.write("        <input type=\"text\" required maxlength=\"50\" class=\"form-control\" id=\"inputEndereco\" placeholder=\"Av Aberlado Bueno 150\"\r\n");
      out.write("          name=\"inputEndereco\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-4\">\r\n");
      out.write("        <label for=\"inputComplemento\" class=\"form-label\">Complemento</label>\r\n");
      out.write("        <input type=\"text\" required maxlength=\"25\" class=\"form-control\" id=\"inputComplemento\" name=\"inputComplemento\"\r\n");
      out.write("          placeholder=\"Bloco, apartamento, casa, etc.\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <label for=\"inputCidade\" class=\"form-label\">Cidade</label>\r\n");
      out.write("        <input type=\"text\" required class=\"form-control\" maxlength=\"30\" id=\"inputCidade\" name=\"inputCidade\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-3\">\r\n");
      out.write("        <label for=\"inputEstado\" class=\"form-label\">Estado</label>\r\n");
      out.write("        <select id=\"inputEstado\" class=\"form-select\" name=\"inputEstado\">\r\n");
      out.write("          <option selected>Selecione o estado</option>\r\n");
      out.write("          ");
      if (_jspx_meth_jstl_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </select>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-3\">\r\n");
      out.write("        <label for=\"inputCep\" class=\"form-label\">Cep</label>\r\n");
      out.write("        <input type=\"text\" maxlength=\"9\" required class=\"form-control\" id=\"inputCep\" name=\"inputCep\">\r\n");
      out.write("      </div>\r\n");
      out.write("    <div class=\"col-12\">\r\n");
      out.write("      <button type=\"submit\" class=\"btn btn-primary\">Cadastrar</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </form>\r\n");
      out.write("  <div>\r\n");
      out.write("  	<div class=\"alert alert-primary my-2\"><a class=\"text-decoration-none\" href=\"../usuario\">Mostrar Usuários cadastrados</a></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("    <footer class=\"py-5 d-flex flex-column align-items-center\">\r\n");
      out.write("        <div class=\"container d-flex justify-content-center flex-wrap gap-5\">\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("                <h4>Vá longe</h4>\r\n");
      out.write("\r\n");
      out.write("                <p>\r\n");
      out.write("                    <a class=\"text-decoration-none text-dark footer_link\" href=\"../sobre.html\">Sobre nós</a>\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <p>SAC 21 2222-2222</p>\r\n");
      out.write("                <p>Atendimento Seg. a Sex: 09h às 19h</p>\r\n");
      out.write("                <p>CNPJ: 42.047.067/0001-21</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("                <h4>Formas de pagamento</h4>\r\n");
      out.write("                <img width=\"300px\" src=\"https://images.tcdn.com.br/img/editor/up/365915/bandeiras_cartoes.png\" alt=\"\" />\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("                <h4>Siga nossas redes</h4>\r\n");
      out.write("                <a href=\"#\" class=\"text-decoration-none\">\r\n");
      out.write("\r\n");
      out.write("                    <img src=\"../assets/images/instagram.png\" alt=\"icone instagram\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"text-decoration-none\">\r\n");
      out.write("\r\n");
      out.write("                    <img src=\"../assets/images/facebook.png\" alt=\"icone facebook\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"text-decoration-none\">\r\n");
      out.write("\r\n");
      out.write("                    <img src=\"../assets/images/youtube.png\" alt=\"icone youtube\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"\">\r\n");
      out.write("            Feito por:\r\n");
      out.write("            <a class=\"text-decoration-none text-dark\" href=\"https://www.linkedin.com/in/maicon-nunes/\" target=\"_blank\">\r\n");
      out.write("                Maicon Nunes\r\n");
      out.write("                <img width=\"40px\" src=\"../assets/images/linkedin.png\" alt=\"icone linkedin\">\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write(" <script>\r\n");
      out.write("    	\r\n");
      out.write("    function mascara(i) {\r\n");
      out.write("\r\n");
      out.write("      var v = i.value;\r\n");
      out.write("\r\n");
      out.write("      if (isNaN(v[v.length - 1])) { // impede entrar outro caractere que não seja número\r\n");
      out.write("        i.value = v.substring(0, v.length - 1);\r\n");
      out.write("        return;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      i.setAttribute(\"maxlength\", \"14\");\r\n");
      out.write("      if (v.length == 3 || v.length == 7) i.value += \".\";\r\n");
      out.write("      if (v.length == 11) i.value += \"-\";\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    const handlePhone = (event) => {\r\n");
      out.write("    	  let input = event.target\r\n");
      out.write("    	  input.value = phoneMask(input.value)\r\n");
      out.write("    	}\r\n");
      out.write("\r\n");
      out.write("    	const phoneMask = (value) => {\r\n");
      out.write("    	  if (!value) return \"\"\r\n");
      out.write("    	  value = value.replace(/\\D/g,'')\r\n");
      out.write("    	  value = value.replace(/(\\d{2})(\\d)/,\"($1) $2\")\r\n");
      out.write("    	  value = value.replace(/(\\d)(\\d{4})$/,\"$1-$2\")\r\n");
      out.write("    	  return value\r\n");
      out.write("    	}\r\n");
      out.write("\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("        integrity=\"sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_jstl_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstl:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_jstl_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fjstl_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_jstl_005fforEach_005f0_reused = false;
    try {
      _jspx_th_jstl_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_jstl_005fforEach_005f0.setParent(null);
      // /usuario/cadastrarUsuario.jsp(115,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_jstl_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/usuario/cadastrarUsuario.jsp(115,10) '${Estados}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${Estados}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /usuario/cadastrarUsuario.jsp(115,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_jstl_005fforEach_005f0.setVar("Estado");
      int[] _jspx_push_body_count_jstl_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_jstl_005fforEach_005f0 = _jspx_th_jstl_005fforEach_005f0.doStartTag();
        if (_jspx_eval_jstl_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("          <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Estado.getDescricao()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Estado.getDescricao()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("          ");
            int evalDoAfterBody = _jspx_th_jstl_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_jstl_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_jstl_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_jstl_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_jstl_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fjstl_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_jstl_005fforEach_005f0);
      _jspx_th_jstl_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_jstl_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_jstl_005fforEach_005f0_reused);
    }
    return false;
  }
}
