/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-11-08 00:31:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.destino;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cadastrarDestino_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../assets/css/style_home.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"./assets/images/logo.png\"\r\n");
      out.write("	type=\"image/x-icon\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<title>Vá longe - Cadastrar destinos</title>\r\n");
      out.write("<style>\r\n");
      out.write("#inputDetalhes {\r\n");
      out.write("	resize: none;\r\n");
      out.write("	height: 120px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<nav class=\"navbar navbar-expand-lg bg-warning\" data-bs-theme=\"dark\">\r\n");
      out.write("			<div class=\"container-fluid\">\r\n");
      out.write("				<a class=\"navbar-brand\" href=\"../index.jsp\"><img\r\n");
      out.write("					src=\"../assets/images/logo.png\" alt=\"logo va longe\"></a>\r\n");
      out.write("				<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("					data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("					aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("					aria-label=\"Toggle navigation\">\r\n");
      out.write("					<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("				</button>\r\n");
      out.write("\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"collapse navbar-collapse  justify-content-end text-center\"\r\n");
      out.write("					id=\"navbarSupportedContent\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<ul class=\"navbar-nav mb-2 mb-lg-0\">\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link style_link_hover\"\r\n");
      out.write("							aria-current=\"page\" href=\"../index.jsp\"> Home</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link style_link_hover\"\r\n");
      out.write("							aria-current=\"page\" href=\"../usuario/cadastrar\"> Cadastrar-se</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link style_link_hover\"\r\n");
      out.write("							href=\"cadastrarDestino.jsp\"> Cadastrar destino </a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link style_link_hover\"\r\n");
      out.write("							href=\"../contact.html\"> Contato </a></li>\r\n");
      out.write("\r\n");
      out.write("					</ul>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</header>\r\n");
      out.write("	<div class=\"container my-5 py-5 border border-primary-subtle rounded\">\r\n");
      out.write("\r\n");
      out.write("		<form class=\"row g-3\" action=\"cadastrar\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-6\">\r\n");
      out.write("				<label for=\"inputPais\" class=\"form-label\">Pais</label> <input\r\n");
      out.write("					type=\"text\" required class=\"form-control\" id=\"inputPais\"\r\n");
      out.write("					name=\"inputPais\">\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-6\">\r\n");
      out.write("				<label for=\"inputCidade\" class=\"form-label\">Cidade</label> <input\r\n");
      out.write("					type=\"text\" required class=\"form-control\" id=\"inputCidade\"\r\n");
      out.write("					name=\"inputCidade\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-md-6\">\r\n");
      out.write("				<label for=\"inputEstado\" class=\"form-label\">Estado</label> <input\r\n");
      out.write("					type=\"text\" required class=\"form-control\" required id=\"inputEstado\"\r\n");
      out.write("					name=\"inputEstado\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-md-6\">\r\n");
      out.write("				<label for=\"inputImg\" class=\"form-label\">Link da imagem </label> <input\r\n");
      out.write("					type=\"text\" required class=\"form-control\" id=\"inputImg\"\r\n");
      out.write("					name=\"inputImg\"\r\n");
      out.write("					placeholder=\"https://magazine.zarpo.com.br/wp-content/uploads/2020/08/Mar-azul-e-ilhas-paradis%C3%ADacas-veja-o-que-fazer-em-Angra-dos-Reis-770x515.jpg\">\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-12\">\r\n");
      out.write("				<label for=\"inputDetalhes\" class=\"form-label\">Detalhes do\r\n");
      out.write("					destino</label>\r\n");
      out.write("				<textarea id=\"inputDetalhes\" class=\"form-control\"\r\n");
      out.write("					name=\"inputDetalhes\">\r\n");
      out.write("      </textarea>\r\n");
      out.write("      <div class=\"col-md-12 my-2\">\r\n");
      out.write("      <h6>Confira sua imagem após colocar o link </h6>\r\n");
      out.write("      <img width=\"200px\" id=\"img\"/>\r\n");
      out.write("      </div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-12\">\r\n");
      out.write("				<button type=\"submit\" class=\"btn btn-primary\">Cadastrar</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("		 <div>\r\n");
      out.write("  	<div class=\"alert alert-primary my-2\"><a class=\"text-decoration-none\" href=\"../destino\">Mostrar Destinos cadastrados</a></div>\r\n");
      out.write("  </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<footer class=\"py-5 d-flex flex-column align-items-center\">\r\n");
      out.write("		<div class=\"container d-flex justify-content-center flex-wrap gap-5\">\r\n");
      out.write("\r\n");
      out.write("			<div>\r\n");
      out.write("				<h4>Vá longe</h4>\r\n");
      out.write("\r\n");
      out.write("				<p>\r\n");
      out.write("					<a class=\"text-decoration-none text-dark footer_link\"\r\n");
      out.write("						href=\"../sobre.html\">Sobre nós</a>\r\n");
      out.write("				</p>\r\n");
      out.write("\r\n");
      out.write("				<p>SAC 21 2222-2222</p>\r\n");
      out.write("				<p>Atendimento Seg. a Sex: 09h às 19h</p>\r\n");
      out.write("				<p>CNPJ: 42.047.067/0001-21</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div>\r\n");
      out.write("				<h4>Formas de pagamento</h4>\r\n");
      out.write("				<img width=\"300px\"\r\n");
      out.write("					src=\"https://images.tcdn.com.br/img/editor/up/365915/bandeiras_cartoes.png\"\r\n");
      out.write("					alt=\"\" />\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div>\r\n");
      out.write("				<h4>Siga nossas redes</h4>\r\n");
      out.write("				<a href=\"#\" class=\"text-decoration-none\"> <img\r\n");
      out.write("					src=\"../assets/images/instagram.png\" alt=\"icone instagram\">\r\n");
      out.write("				</a> <a href=\"#\" class=\"text-decoration-none\"> <img\r\n");
      out.write("					src=\"../assets/images/facebook.png\" alt=\"icone facebook\">\r\n");
      out.write("				</a> <a href=\"#\" class=\"text-decoration-none\"> <img\r\n");
      out.write("					src=\"../assets/images/youtube.png\" alt=\"icone youtube\">\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"\">\r\n");
      out.write("			Feito por: <a class=\"text-decoration-none text-dark\"\r\n");
      out.write("				href=\"https://www.linkedin.com/in/maicon-nunes/\" target=\"_blank\">\r\n");
      out.write("				Maicon Nunes <img width=\"40px\" src=\"../assets/images/linkedin.png\"\r\n");
      out.write("				alt=\"icone linkedin\">\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	\r\n");
      out.write("  <script>\r\n");
      out.write("    const inputImg = document.getElementById('inputImg');\r\n");
      out.write("    inputImg.addEventListener('keyup', () => {\r\n");
      out.write("      const img = document.getElementById(\"img\");\r\n");
      out.write("      img.setAttribute('src', inputImg.value);\r\n");
      out.write("    })\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
