/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-11-07 00:18:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("	\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-BR\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Vá longe - Transformando sua viagem em uma experiência incrivel</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/style_home.css\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("        integrity=\"sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"./assets/images/logo.png\" type=\"image/x-icon\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Classe com \"_\" substituindo \"-\" criado no css, não no bootstrap  -->\r\n");
      out.write("    <!-- Criando o cabeçalho -->\r\n");
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg\" data-bs-theme=\"dark\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"index.jsp\"><img src=\"assets/images/logo.png\" alt=\"logo va longe\"></a>\r\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("                    data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\"\r\n");
      out.write("                    aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"collapse navbar-collapse  justify-content-end text-center\" id=\"navbarSupportedContent\">\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                    <ul class=\"navbar-nav mb-2 mb-lg-0\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link style_link_hover\" aria-current=\"page\" href=\"index.jsp\">\r\n");
      out.write("                                Home</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link style_link_hover\" aria-current=\"page\" href=\"usuario/cadastrar\">\r\n");
      out.write("                                Cadastrar-se</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link style_link_hover\" href=\"destino/cadastrarDestino.jsp\">\r\n");
      out.write("                                Cadastrar destino\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link style_link_hover\" href=\"contact.html\">\r\n");
      out.write("                                Contato\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                       \r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- Fim do cabeçalho -->\r\n");
      out.write("    <section class=\"section_img\">\r\n");
      out.write("        <div class=\"folder_container d-flex flex-column justify-content-center mb-auto ms-5\">\r\n");
      out.write("            <div class=\"d-flex flex-column mt-3 justify-content-center\">\r\n");
      out.write("                <h2>Descubra o Mundo com a Nossa Agência de Viagens!</h2>\r\n");
      out.write("                <h4>Seja aventureiro(a) ou em busca de relaxamento, nossa agência de viagens\r\n");
      out.write("                    é\r\n");
      out.write("                    sua parceira ideal para desvendar os segredos do mundo. Oferecemos roteiros exclusivos,\r\n");
      out.write("                    acomodações\r\n");
      out.write("                    de luxo e experiências inesquecíveis. Viaje com segurança, conforto e uma equipe dedicada ao seu\r\n");
      out.write("                    bem-estar. Aventure-se em destinos exóticos e viva momentos únicos</h4>\r\n");
      out.write("                <!-- <p class=\"fs-4\">Liberte-se da rotina e embarque em uma jornada única! Descubra paisagens\r\n");
      out.write("                        deslumbrantes, culturas\r\n");
      out.write("                        fascinantes e momentos inesquecíveis. Aproveite agora a oportunidade de viver aventuras\r\n");
      out.write("                        extraordinárias\r\n");
      out.write("                        com nossas irresistíveis ofertas de viagens. Seu destino dos sonhos está apenas a um passo de\r\n");
      out.write("                        distância.\r\n");
      out.write("                    </p> -->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"destiny.html\" class=\"btn btn-primary\">Descubra Agora!</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <main class=\"px-5 mb-5\">\r\n");
      out.write("\r\n");
      out.write("        <!-- container das informações -->\r\n");
      out.write("\r\n");
      out.write("        <section class=\"d-flex justify-content-around flex-wrap info_container p-3\">\r\n");
      out.write("            <span class=\"\"><img class=\"pe-2\" src=\"assets/images/aviao.png\" alt=\"icone aviao\" />Viagens para qualquer\r\n");
      out.write("                lugar do mundo</span>\r\n");
      out.write("            <span><img class=\"pe-2\" src=\"assets/images/carteira.png\" alt=\"icone carteira\">Parcelamento em até 12x sem\r\n");
      out.write("                juros</span>\r\n");
      out.write("            <span><img class=\"pe-2\" src=\"assets/images/seguranca.png\" alt=\"icone de cartão com cadeado\">Sua compra\r\n");
      out.write("                totalmente\r\n");
      out.write("                segura</span>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"container d-flex flex-column gap-5 my-5\">\r\n");
      out.write("            <div class=\"card-info-trip\">\r\n");
      out.write("                <img src=\"assets/images/card1.jpg\" alt=\"Foto de praia paradisiaca\">\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h2>Oferta Imperdível - Pacotes de Praia com Descontos Incríveis.</h2>\r\n");
      out.write("                    <p>Aproveite a temporada de sol e mar com nossas ofertas especiais para destinos de praia\r\n");
      out.write("                        deslumbrantes. Reserve agora e economize até 30% nos pacotes completos, que incluem passagens,\r\n");
      out.write("                        hospedagens e passeios emocionantes. Garanta seu lugar no paraíso e desfrute de momentos\r\n");
      out.write("                        relaxantes e revigorantes.</p>\r\n");
      out.write("                    <button class=\"btn btn-primary\" type=\"button\">Reserve Já</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card-info-trip\">\r\n");
      out.write("                <img src=\"assets/images/card2.jpg\" alt=\"Foto de praia paradisiaca\">\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h2>Viaje no Tempo - Explore a História de Destinos Culturais</h2>\r\n");
      out.write("                    <p>Se você é fascinado(a) pela história e cultura dos lugares, temos o itinerário perfeito para\r\n");
      out.write("                        você! Visite cidades encantadoras, repletas de monumentos e maravilhas arquitetônicas. Nossos\r\n");
      out.write("                        guias especializados conduzirão você através de séculos de histórias intrigantes. Embarque nessa\r\n");
      out.write("                        jornada única e sinta-se parte do passado!</p>\r\n");
      out.write("                    <button class=\"btn btn-primary\" type=\"button\">Reserve Já</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card-info-trip\">\r\n");
      out.write("                <img src=\"assets/images/card3.jpg\" alt=\"Foto de praia paradisiaca\">\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h2>Emoção e Adrenalina - Destinos Perfeitos para Aventureiros</h2>\r\n");
      out.write("                    <p>Para os espíritos aventureiros, temos destinos que testarão seus limites e proporcionarão\r\n");
      out.write("                        experiências eletrizantes. Explore trilhas selvagens, mergulhe em rios cristalinos e desafie-se\r\n");
      out.write("                        em esportes radicais. Oferecemos pacotes personalizados para aqueles que buscam o máximo de\r\n");
      out.write("                        emoção</p>\r\n");
      out.write("                    <button class=\"btn btn-primary\" type=\"button\">Reserve Já</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card-info-trip\">\r\n");
      out.write("                <img src=\"assets/images/card4.jpg\" alt=\"Foto de praia paradisiaca\">\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h2>Momentos Inesquecíveis em Família - Viagens para Todos.</h2>\r\n");
      out.write("                    <p>Nossa agência tem as melhores opções para viagens em família! Proporcionamos momentos de alegria\r\n");
      out.write("                        e conexão, com roteiros cuidadosamente selecionados para todas as idades. Desfrute de parques\r\n");
      out.write("                        temáticos, atividades recreativas e destinos amigáveis para crianças. Crie memórias\r\n");
      out.write("                        inesquecíveis com quem você ama.</p>\r\n");
      out.write("                    <button class=\"btn btn-primary\" type=\"button\">Reserve Já</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card-info-trip\">\r\n");
      out.write("                <img src=\"assets/images/card5.jpg\" alt=\"Foto de praia paradisiaca\">\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h2>Experiências Sofisticadas - Viagens de Luxo para os Exigentes.</h2>\r\n");
      out.write("                    <p>Oferecemos um toque de requinte para viajantes que apreciam o luxo. Nossos pacotes exclusivos\r\n");
      out.write("                        incluem hospedagens em hotéis de alto padrão, serviços personalizados e experiências únicas que\r\n");
      out.write("                        só os viajantes mais exigentes podem desfrutar. Mime-se com o melhor que o mundo tem a oferecer.\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <button class=\"btn btn-primary\" type=\"button\">Reserve Já</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <!-- Cards das promoções -->\r\n");
      out.write("        <section>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                <h4>Promoções</h4>\r\n");
      out.write("                <a class=\"link icon icon-link-hover text-decoration-none\" href=\"sales.html\">\r\n");
      out.write("                    Ver mais\r\n");
      out.write("                    <img class=\"img_link bi\" aria-hidden=\"true\" src=\"./assets/images/seta.png\" alt=\"\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mt-3 d-flex flex-wrap justify-content-evenly gap-5 \">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card position-relative card_sale\" style=\"width: 18rem;\">\r\n");
      out.write("                    <div class=\"position-absolute d-flex flex-column btn_card_absolute\">\r\n");
      out.write("                        <p class=\"btn btn-warning\">Pacotes Nacionais</p>\r\n");
      out.write("                        <p class=\"btn btn-danger\">-50%</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card_sales_img\">\r\n");
      out.write("                        <img src=\"assets/images/bauneario.jpg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h5 class=\"card-title\">Bauneário Camboriú</h5>\r\n");
      out.write("                        <p class=\"card-text\"><img class=\"me-1\" width=\"22px\" src=\"assets/images/mala.png\"\r\n");
      out.write("                                alt=\"icone mala\"> 4 diárias\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <ul class=\"card_list_sale\">\r\n");
      out.write("                            <li>Passagem aérea</li>\r\n");
      out.write("                            <li>Hospedagem</li>\r\n");
      out.write("                            <li>Café da manhã</li>\r\n");
      out.write("                            <li>Open bar</li>\r\n");
      out.write("                            <li>Saindo de São Paulo</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <span>\r\n");
      out.write("                                <s>de R$ 2150,00</s>\r\n");
      out.write("                            </span>\r\n");
      out.write("\r\n");
      out.write("                            <div><small>por</small>\r\n");
      out.write("                                <span class=\"fs-3 card_sale_price text-warning\">R$ 1075,00</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <span></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card position-relative card_sale\" style=\"width: 18rem;\">\r\n");
      out.write("                    <div class=\"position-absolute d-flex flex-column btn_card_absolute\">\r\n");
      out.write("                        <p class=\"btn btn-primary\">Pacotes Internacionais</p>\r\n");
      out.write("                        <p class=\"btn btn-danger\">-20%</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card_sales_img\">\r\n");
      out.write("                        <img src=\"assets/images/dubai.jpg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h5 class=\"card-title\">Dubai</h5>\r\n");
      out.write("                        <p class=\"card-text\"><img class=\"me-1\" width=\"22px\" src=\"assets/images/mala.png\"\r\n");
      out.write("                                alt=\"icone mala\"> 7 diárias\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <ul class=\"card_list_sale\">\r\n");
      out.write("                            <li>Passagem aérea</li>\r\n");
      out.write("                            <li>Hospedagem</li>\r\n");
      out.write("                            <li>Saindo de Rio de Janeiro</li>\r\n");
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <span>\r\n");
      out.write("                                <s>de R$ 15.850,90</s>\r\n");
      out.write("                            </span>\r\n");
      out.write("\r\n");
      out.write("                            <div><small>por</small>\r\n");
      out.write("                                <span class=\"fs-3 card_sale_price text-warning\">R$ 12.680,72</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <span></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card position-relative card_sale\" style=\"width: 18rem;\">\r\n");
      out.write("                    <div class=\"position-absolute d-flex flex-column btn_card_absolute\">\r\n");
      out.write("                        <p class=\"btn btn-warning\">Pacotes Nacionais</p>\r\n");
      out.write("                        <p class=\"btn btn-danger\">-10%</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card_sales_img\">\r\n");
      out.write("                        <img src=\"assets/images/cruzeiro.jpeg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h5 class=\"card-title\">Cruzeiro Preziosa - Ilha Bela</h5>\r\n");
      out.write("                        <p class=\"card-text\"><img class=\"me-1\" width=\"22px\" src=\"assets/images/mala.png\"\r\n");
      out.write("                                alt=\"icone mala\"> 4 diárias\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <ul class=\"card_list_sale\">\r\n");
      out.write("                            <li>All incluse</li>\r\n");
      out.write("                            <li>Saindo de Santos</li>\r\n");
      out.write("                            <li>Ilhabela</li>\r\n");
      out.write("                            <li>Ilha grande</li>\r\n");
      out.write("                            <li>Desembarque Santos</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <span>\r\n");
      out.write("                                <s>de R$ 3250,90</s>\r\n");
      out.write("                            </span>\r\n");
      out.write("\r\n");
      out.write("                            <div><small>por</small>\r\n");
      out.write("                                <span class=\"fs-3 card_sale_price text-warning\">R$ 2925,81</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <span></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card position-relative card_sale\" style=\"width: 18rem;\">\r\n");
      out.write("                    <div class=\"position-absolute d-flex flex-column btn_card_absolute\">\r\n");
      out.write("                        <p class=\"btn btn-warning\">Pacotes Nacionais</p>\r\n");
      out.write("                        <p class=\"btn btn-danger\">-30%</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card_sales_img\">\r\n");
      out.write("                        <img src=\"assets/images/rj.jpg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h5 class=\"card-title\">Rio de Janeiro</h5>\r\n");
      out.write("                        <p class=\"card-text\"><img class=\"me-1\" width=\"22px\" src=\"assets/images/mala.png\"\r\n");
      out.write("                                alt=\"icone mala\">\r\n");
      out.write("                            3 diárias\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <ul class=\"card_list_sale\">\r\n");
      out.write("                            <li>Passagem aérea</li>\r\n");
      out.write("                            <li>Hospedagem</li>\r\n");
      out.write("                            <li>Café da manhã</li>\r\n");
      out.write("                            <li>Saindo de São Paulo</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <span>\r\n");
      out.write("                                <s>de R$ 2150,00</s>\r\n");
      out.write("                            </span>\r\n");
      out.write("\r\n");
      out.write("                            <div><small>por</small>\r\n");
      out.write("                                <span class=\"fs-3 card_sale_price text-warning\">R$ 1505,00</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <span></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card position-relative card_sale\" style=\"width: 18rem;\">\r\n");
      out.write("                    <div class=\"position-absolute d-flex flex-column btn_card_absolute\">\r\n");
      out.write("                        <p class=\"btn btn-primary\">Pacotes Internacionais</p>\r\n");
      out.write("                        <p class=\"btn btn-danger\">-15%</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card_sales_img\">\r\n");
      out.write("\r\n");
      out.write("                        <img src=\"assets/images/cancun.jpg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h5 class=\"card-title\">Cancun</h5>\r\n");
      out.write("                        <p class=\"card-text\"><img class=\"me-1\" width=\"22px\" src=\"assets/images/mala.png\"\r\n");
      out.write("                                alt=\"icone mala\"> 5 diárias\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <ul class=\"card_list_sale\">\r\n");
      out.write("                            <li>Passagem aérea</li>\r\n");
      out.write("                            <li>Hospedagem</li>\r\n");
      out.write("                            <li>Café da manhã</li>\r\n");
      out.write("                            <li>Saindo de Florianópolis</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <span>\r\n");
      out.write("                                <s>de R$ 8250,00</s>\r\n");
      out.write("                            </span>\r\n");
      out.write("\r\n");
      out.write("                            <div><small>por</small>\r\n");
      out.write("                                <span class=\"fs-3 card_sale_price text-warning\">R$ 7012,50</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <span></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card position-relative card_sale\" style=\"width: 18rem;\">\r\n");
      out.write("                    <div class=\"position-absolute d-flex flex-column btn_card_absolute\">\r\n");
      out.write("                        <p class=\"btn btn-primary\">Pacotes Internacionais</p>\r\n");
      out.write("                        <p class=\"btn btn-danger\">-10%</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card_sales_img\">\r\n");
      out.write("\r\n");
      out.write("                        <img src=\"assets/images/roma.jpg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h5 class=\"card-title\">Roma</h5>\r\n");
      out.write("                        <p class=\"card-text\"><img class=\"me-1\" width=\"22px\" src=\"assets/images/mala.png\"\r\n");
      out.write("                                alt=\"icone mala\"> 6 diárias\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <ul class=\"card_list_sale\">\r\n");
      out.write("                            <li>Passagem aérea</li>\r\n");
      out.write("                            <li>Hospedagem</li>\r\n");
      out.write("                            <li>Café da manhã</li>\r\n");
      out.write("                            <li>Saindo de Salvador</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <span>\r\n");
      out.write("                                <s>de R$ 17.044,00</s>\r\n");
      out.write("                            </span>\r\n");
      out.write("\r\n");
      out.write("                            <div><small>por</small>\r\n");
      out.write("                                <span class=\"fs-3 card_sale_price text-warning\">R$ 15.339,60</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <span></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Cards destinos -->\r\n");
      out.write("        <section class=\"mt-5\">\r\n");
      out.write("            <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                <h4>Destinos</h4>\r\n");
      out.write("                <a class=\"link icon icon-link-hover text-decoration-none\" href=\"destinos.html\">\r\n");
      out.write("                    Ver mais\r\n");
      out.write("                    <img class=\"img_link bi\" aria-hidden=\"true\" src=\"./assets/images/seta.png\" alt=\"\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"d-flex flex-wrap justify-content-evenly gap-5 mt-3\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card position-relative overflow-hidden card_destiny\" style=\"width: 18rem;\">\r\n");
      out.write("\r\n");
      out.write("                    <img width=\"100%\" height=\"100%\" src=\"assets/images/paris.jpg\" class=\"position-absolute\" alt=\"...\">\r\n");
      out.write("                    <div class=\"z-1 d-flex h-100 flex-column justify-content-end align-items-center mb-3\">\r\n");
      out.write("                        <p class=\"text-warning mb-0\">PACOTES PARA</p>\r\n");
      out.write("                        <h3 class=\"text-white fs-1\">Paris</h3>\r\n");
      out.write("                        <a href=\"#\" class=\"btn btn-warning text-white\">Conferir</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card position-relative overflow-hidden card_destiny\" style=\"width: 18rem;\">\r\n");
      out.write("\r\n");
      out.write("                    <img width=\"100%\" height=\"100%\" src=\"assets/images/vegas.jpg\" class=\"position-absolute\" alt=\"...\">\r\n");
      out.write("                    <div class=\"z-1 d-flex h-100 flex-column justify-content-end align-items-center mb-3\">\r\n");
      out.write("                        <p class=\"text-warning mb-0\">PACOTES PARA</p>\r\n");
      out.write("                        <h3 class=\"text-white fs-1\">Las Vegas</h3>\r\n");
      out.write("                        <a href=\"#\" class=\"btn btn-warning text-white\">Conferir</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card position-relative overflow-hidden card_destiny\" style=\"width: 18rem;\">\r\n");
      out.write("\r\n");
      out.write("                    <img width=\"100%\" height=\"100%\" src=\"assets/images/maceio.jpeg\" class=\"position-absolute\" alt=\"...\">\r\n");
      out.write("                    <div class=\"z-1 d-flex h-100 flex-column justify-content-end align-items-center mb-3\">\r\n");
      out.write("                        <p class=\"text-warning mb-0\">PACOTES PARA</p>\r\n");
      out.write("                        <h3 class=\"text-white fs-1\">Maceió</h3>\r\n");
      out.write("                        <a href=\"#\" class=\"btn btn-warning text-white\">Conferir</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card position-relative overflow-hidden card_destiny\" style=\"width: 18rem;\">\r\n");
      out.write("\r\n");
      out.write("                    <img width=\"100%\" height=\"100%\" src=\"assets/images/orlando.jpg\" class=\"position-absolute\" alt=\"...\">\r\n");
      out.write("                    <div class=\"z-1 d-flex h-100 flex-column justify-content-end align-items-center mb-3\">\r\n");
      out.write("                        <p class=\"text-warning mb-0\">PACOTES PARA</p>\r\n");
      out.write("                        <h3 class=\"text-white fs-1\">Orlando</h3>\r\n");
      out.write("                        <a href=\"#\" class=\"btn btn-warning text-white\">Conferir</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card position-relative overflow-hidden card_destiny\" style=\"width: 18rem;\">\r\n");
      out.write("\r\n");
      out.write("                    <img width=\"100%\" height=\"100%\" src=\"assets/images/aruba.jpeg\" class=\"position-absolute\" alt=\"...\">\r\n");
      out.write("                    <div class=\"z-1 d-flex h-100 flex-column justify-content-end align-items-center mb-3\">\r\n");
      out.write("                        <p class=\"text-warning mb-0\">PACOTES PARA</p>\r\n");
      out.write("                        <h3 class=\"text-white fs-1\">Aruba</h3>\r\n");
      out.write("                        <a href=\"#\" class=\"btn btn-warning text-white\">Conferir</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card position-relative overflow-hidden card_destiny\" style=\"width: 18rem;\">\r\n");
      out.write("\r\n");
      out.write("                    <img width=\"100%\" height=\"100%\" src=\"assets/images/lisboa.jpg\" class=\"position-absolute\" alt=\"...\">\r\n");
      out.write("                    <div class=\"z-1 d-flex h-100 flex-column justify-content-end align-items-center mb-3\">\r\n");
      out.write("                        <p class=\"text-warning mb-0\">PACOTES PARA</p>\r\n");
      out.write("                        <h3 class=\"text-white fs-1\">Lisboa</h3>\r\n");
      out.write("                        <a href=\"#\" class=\"btn btn-warning text-white\">Conferir</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <!-- Rodapé -->\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"py-5 d-flex flex-column align-items-center\">\r\n");
      out.write("        <div class=\"container d-flex justify-content-center flex-wrap gap-5\">\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("                <h4>Vá longe</h4>\r\n");
      out.write("\r\n");
      out.write("                <p>\r\n");
      out.write("                    <a class=\"text-decoration-none text-dark footer_link\" href=\"sobre.html\">Sobre nós</a>\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                <p>SAC 21 2222-2222</p>\r\n");
      out.write("                <p>Atendimento Seg. a Sex: 09h às 19h</p>\r\n");
      out.write("                <p>CNPJ: 42.047.067/0001-21</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("                <h4>Formas de pagamento</h4>\r\n");
      out.write("                <img width=\"300px\" src=\"https://images.tcdn.com.br/img/editor/up/365915/bandeiras_cartoes.png\" alt=\"\" />\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("                <h4>Siga nossas redes</h4>\r\n");
      out.write("                <a href=\"#\" class=\"text-decoration-none\">\r\n");
      out.write("\r\n");
      out.write("                    <img src=\"assets/images/instagram.png\" alt=\"icone instagram\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"text-decoration-none\">\r\n");
      out.write("\r\n");
      out.write("                    <img src=\"assets/images/facebook.png\" alt=\"icone facebook\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"text-decoration-none\">\r\n");
      out.write("\r\n");
      out.write("                    <img src=\"assets/images/youtube.png\" alt=\"icone youtube\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"\">\r\n");
      out.write("            Feito por:\r\n");
      out.write("            <a class=\"text-decoration-none text-dark\" href=\"https://www.linkedin.com/in/maicon-nunes/\" target=\"_blank\">\r\n");
      out.write("                Maicon Nunes\r\n");
      out.write("                <img width=\"40px\" src=\"assets/images/linkedin.png\" alt=\"icone linkedin\">\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("        integrity=\"sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
